version: "3.9"

services:
  mysql:
    container_name: mysqlDB
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=root  
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local